//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppLab1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Aidat
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string blok { get; set; }
        public Nullable<int> daire { get; set; }
        public string aidat { get; set; }
    
        public virtual Site_Kullanici Site_Kullanici { get; set; }
    }
}
