//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppLab1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteYönetimWPDBEntities : DbContext
    {
        public SiteYönetimWPDBEntities()
            : base("name=SiteYönetimWPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Site_Kullanici> Site_Kullanici { get; set; }
        public virtual DbSet<Site_Aidat> Site_Aidat { get; set; }
    }
}
